INSERT INTO customer (id, name, email) VALUES
(1, 'Mariazinha', 'mariazinha@email.com'),
(2, 'Alice', 'alice@email.com'),
(3, 'Miguel', 'miguel@email.com'),
(4, 'Sophia', 'sophia@email.com'),
(5, 'Arthur', 'arthur@email.com'),
(6, 'Helena', 'helena@email.com'),
(7, 'Bernardo', 'bernardo@email.com'),
(8, 'Valentina', 'valentina@email.com'),
(9, 'Heitor', 'heitor@email.com'),
(10, 'Laura', 'laura@email.com'),
(11, 'Davi', 'davi@email.com'),
(12, 'Isabella', 'isabella@email.com'),
(13, 'Lorenzo', 'lorenzo@email.com'),
(14, 'Manuela', 'manuela@email.com'),
(15, 'Theo', 'theo@email.com'),
(16, 'Julia', 'julia@email.com'),
(17, 'Pedro', 'pedro@email.com'),
(18, 'Heloisa', 'heloisa@email.com'),
(19, 'Gabriel', 'gabriel@email.com'),
(20, 'Luiza', 'luiza@email.com'),
(21, 'Enzo', 'enzo@email.com'),
(22, 'Maria Luiza', 'marialuiza@email.com'),
(23, 'Matheus', 'matheus@email.com'),
(24, 'Lorena', 'lorena@email.com'),
(25, 'Lucas', 'lucas@email.com'),
(26, 'Livia', 'livia@email.com'),
(27, 'Benjamin', 'benjamin@email.com'),
(28, 'Joel', 'joel@email.com'),
(29, 'Lea', 'lea@email.com'),
(30, 'Joãozinho', 'joaozinho@email.com');

INSERT INTO endereco (id, cep) VALUES
(1, 02420001);